export const departments = [
  "engineering",
  "design",
  "marketing",
  "product",
  "sales",
  "hr",
  "finance",
];

export const skillsList = {
  engineering: ["JavaScript", "React", "Node.js", "Python", "AWS", "DevOps"],
  design: ["UI/UX", "Figma", "Adobe XD", "Photoshop", "Illustration"],
  marketing: [
    "Content Strategy",
    "SEO",
    "Social Media",
    "Analytics",
    "Email Marketing",
  ],
  product: ["Product Strategy", "Agile", "User Research", "Roadmapping"],
  sales: ["Lead Generation", "Negotiation", "CRM", "Sales Strategy"],
  hr: ["Recruitment", "Employee Relations", "Training", "Compensation"],
  finance: ["Financial Planning", "Budgeting", "Analysis", "Reporting"],
};

export const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "admin",
    avatar:
      "https://ui-avatars.com/api/?name=John+Doe&background=0D8ABC&color=fff",
    department: "engineering",
    position: "Engineering Manager",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    bio: "Experienced engineering manager with a passion for building great products and teams.",
    skills: ["JavaScript", "React", "Node.js", "Team Leadership", "Agile"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/johndoe",
      github: "https://github.com/johndoe",
      twitter: "https://twitter.com/johndoe",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "09:00",
      timezone: "America/Los_Angeles",
    },
    stats: {
      projectsLed: 12,
      teamSize: 8,
      yearsOfExperience: 10,
    },
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "employee",
    avatar:
      "https://ui-avatars.com/api/?name=Jane+Smith&background=6366F1&color=fff",
    department: "design",
    position: "Senior UI/UX Designer",
    phone: "+1 (555) 234-5678",
    location: "New York, NY",
    bio: "Creative designer focused on creating beautiful and intuitive user experiences.",
    skills: ["UI/UX", "Figma", "Adobe XD", "User Research", "Prototyping"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/janesmith",
      dribbble: "https://dribbble.com/janesmith",
      behance: "https://behance.net/janesmith",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "08:30",
      timezone: "America/New_York",
    },
    stats: {
      designSystems: 5,
      completedProjects: 45,
      yearsOfExperience: 7,
    },
  },
  {
    id: "3",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "employee",
    avatar:
      "https://ui-avatars.com/api/?name=Alice+Johnson&background=10B981&color=fff",
    department: "marketing",
    position: "Marketing Specialist",
    phone: "+1 (555) 345-6789",
    location: "Chicago, IL",
    bio: "Digital marketing expert specializing in growth strategies and content creation.",
    skills: [
      "Content Strategy",
      "SEO",
      "Social Media",
      "Email Marketing",
      "Analytics",
    ],
    socialLinks: {
      linkedin: "https://linkedin.com/in/alicejohnson",
      twitter: "https://twitter.com/alicejohnson",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "09:30",
      timezone: "America/Chicago",
    },
    stats: {
      campaigns: 24,
      contentPieces: 150,
      yearsOfExperience: 5,
    },
  },
  {
    id: "4",
    name: "Bob Wilson",
    email: "bob@example.com",
    role: "employee",
    avatar:
      "https://ui-avatars.com/api/?name=Bob+Wilson&background=EF4444&color=fff",
    department: "engineering",
    position: "Senior Developer",
    phone: "+1 (555) 456-7890",
    location: "Austin, TX",
    bio: "Full-stack developer with expertise in modern web technologies and cloud architecture.",
    skills: ["Python", "AWS", "DevOps", "React", "Node.js", "MongoDB"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/bobwilson",
      github: "https://github.com/bobwilson",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "10:00",
      timezone: "America/Chicago",
    },
    stats: {
      codeReviews: 500,
      pullRequests: 300,
      yearsOfExperience: 8,
    },
  },
];

export const mockProjects = [
  {
    id: "1",
    name: "Website Redesign",
    description: "Complete redesign of the company website",
    startDate: "2024-01-15",
    endDate: "2024-03-15",
    status: "progress",
    progress: 65,
    teamMembers: ["2", "3"],
    createdBy: "1",
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    name: "Mobile App Development",
    description: "Development of the iOS and Android mobile application",
    startDate: "2024-02-01",
    endDate: "2024-05-01",
    status: "progress",
    progress: 30,
    teamMembers: ["4", "2"],
    createdBy: "1",
    createdAt: "2024-01-25",
  },
  {
    id: "3",
    name: "Marketing Campaign",
    description: "Q1 marketing campaign planning and execution",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
    status: "completed",
    progress: 100,
    teamMembers: ["3"],
    createdBy: "1",
    createdAt: "2023-12-15",
  },
];

export const mockTasks = [
  {
    id: "1",
    title: "Create wireframes for homepage",
    description: "Design initial wireframes for the new homepage layout",
    status: "todo",
    priority: "high",
    assignee: "2",
    project: "1",
    dueDate: "2024-01-20",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    createdBy: "1",
  },
  {
    id: "2",
    title: "Implement user authentication",
    description: "Set up user login and registration system",
    status: "progress",
    priority: "urgent",
    assignee: "4",
    project: "2",
    dueDate: "2024-02-10",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-05",
    createdBy: "1",
  },
  {
    id: "3",
    title: "Write unit tests",
    description:
      "Create comprehensive unit tests for the authentication module",
    status: "review",
    priority: "medium",
    assignee: "2",
    project: "2",
    dueDate: "2024-02-15",
    createdAt: "2024-02-08",
    updatedAt: "2024-02-12",
    createdBy: "1",
  },
  {
    id: "4",
    title: "Design marketing materials",
    description: "Create brochures and digital assets for the campaign",
    status: "completed",
    priority: "medium",
    assignee: "3",
    project: "3",
    dueDate: "2024-01-25",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-24",
    createdBy: "1",
  },
  {
    id: "5",
    title: "Setup database schema",
    description: "Design and implement the database structure",
    status: "progress",
    priority: "high",
    assignee: "4",
    project: "2",
    dueDate: "2024-02-05",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    createdBy: "1",
  },
  {
    id: "6",
    title: "Content creation",
    description: "Write and optimize content for the new website",
    status: "review",
    priority: "medium",
    assignee: "3",
    project: "1",
    dueDate: "2024-02-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15",
    createdBy: "1",
  },
  {
    id: "7",
    title: "Content creation",
    description: "Write and optimize content for the new website",
    status: "completed",
    priority: "medium",
    assignee: "3",
    project: "1",
    dueDate: "2024-02-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15",
    createdBy: "1",
  },
  {
    id: "8",
    title: "Content creation",
    description: "Write and optimize content for the new website",
    status: "todo",
    priority: "medium",
    assignee: "3",
    project: "1",
    dueDate: "2024-02-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15",
    createdBy: "1",
  },
];

export const mockConversations = [
  {
    id: "1",
    name: "Development Team",
    type: "group",
    participants: ["1", "2", "4"],
    lastMessage: "Great progress on the authentication module!",
    lastMessageTime: "2024-01-15 14:30",
    unreadCount: 2,
  },
  {
    id: "2",
    name: "Jane Smith",
    type: "individual",
    participants: ["1", "2"],
    lastMessage: "Can we schedule a meeting to discuss the wireframes?",
    lastMessageTime: "2024-01-15 11:20",
    unreadCount: 1,
  },
  {
    id: "3",
    name: "Project Updates",
    type: "group",
    participants: ["1", "2", "3", "4"],
    lastMessage: "Marketing campaign is now complete!",
    lastMessageTime: "2024-01-14 16:45",
    unreadCount: 0,
  },
];

export const mockMessages = [
  {
    id: "1",
    conversationId: "1",
    senderId: "1",
    content: "Good morning team! How is everyone doing with their tasks?",
    timestamp: "2024-01-15 09:00",
    type: "text",
  },
  {
    id: "2",
    conversationId: "1",
    senderId: "4",
    content:
      "Working on the authentication module. Should be ready for testing by tomorrow.",
    timestamp: "2024-01-15 09:15",
    type: "text",
  },
  {
    id: "3",
    conversationId: "1",
    senderId: "2",
    content:
      "Wireframes are coming along nicely. Will share them this afternoon.",
    timestamp: "2024-01-15 09:30",
    type: "text",
  },
  {
    id: "4",
    conversationId: "1",
    senderId: "1",
    content: "Great progress on the authentication module!",
    timestamp: "2024-01-15 14:30",
    type: "text",
  },
  {
    id: "5",
    conversationId: "2",
    senderId: "2",
    content:
      "Hi John, I have completed the initial wireframes for the homepage.",
    timestamp: "2024-01-15 10:00",
    type: "text",
  },
  {
    id: "6",
    conversationId: "2",
    senderId: "1",
    content: "That's excellent! Could you share them with me?",
    timestamp: "2024-01-15 10:15",
    type: "text",
  },
  {
    id: "7",
    conversationId: "2",
    senderId: "2",
    content: "Can we schedule a meeting to discuss the wireframes?",
    timestamp: "2024-01-15 11:20",
    type: "text",
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "task_completed",
    title: "Task Completed",
    message: 'Jane Smith completed "Design marketing materials"',
    timestamp: "2024-01-15 14:30",
    read: false,
    userId: "1",
  },
  {
    id: "2",
    type: "task_assigned",
    title: "New Task Assigned",
    message: 'You have been assigned to "Create wireframes for homepage"',
    timestamp: "2024-01-15 09:00",
    read: false,
    userId: "2",
  },
  {
    id: "3",
    type: "project_created",
    title: "New Project Created",
    message: "Mobile App Development project has been created",
    timestamp: "2024-01-14 16:00",
    read: true,
    userId: "1",
  },
];

export const generateMockData = () => {
  return {
    users: mockUsers,
    projects: mockProjects,
    tasks: mockTasks,
    conversations: mockConversations,
    messages: mockMessages,
    notifications: mockNotifications,
  };
};
