export const departments = [
  "engineering",
  "design",
  "marketing",
  "product",
  "sales",
  "hr",
  "finance",
];

export const teams = [
  {
    id: "team-1",
    name: "Engineering Team",
    department: "engineering",
    manager: "account_manager_1",
    members: ["1", "4", "5", "6"],
  },
  {
    id: "team-2",
    name: "Design Team",
    department: "design",
    manager: "account_manager_2",
    members: ["2", "7", "8"],
  },
  {
    id: "team-3",
    name: "Marketing Team",
    department: "marketing",
    manager: "account_manager_3",
    members: ["3", "9", "10"],
  },
  {
    id: "team-4",
    name: "Sales Team",
    department: "sales",
    manager: "account_manager_4",
    members: ["11", "12", "13"],
  },
];

export const skillsList = {
  engineering: ["JavaScript", "React", "Node.js", "Python", "AWS", "DevOps"],
  design: ["UI/UX", "Figma", "Adobe XD", "Photoshop", "Illustration"],
  marketing: [
    "Content Strategy",
    "SEO",
    "Social Media",
    "Analytics",
    "Email Marketing",
  ],
  product: ["Product Strategy", "Agile", "User Research", "Roadmapping"],
  sales: ["Lead Generation", "Negotiation", "CRM", "Sales Strategy"],
  hr: ["Recruitment", "Employee Relations", "Training", "Compensation"],
  finance: ["Financial Planning", "Budgeting", "Analysis", "Reporting"],
};

export const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "admin",
    avatar:
      "https://ui-avatars.com/api/?name=John+Doe&background=0D8ABC&color=fff",
    department: "engineering",
    position: "Engineering Manager",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    bio: "Experienced engineering manager with a passion for building great products and teams.",
    skills: ["JavaScript", "React", "Node.js", "Team Leadership", "Agile"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/johndoe",
      github: "https://github.com/johndoe",
      twitter: "https://twitter.com/johndoe",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "09:00",
      timezone: "America/Los_Angeles",
    },
    stats: {
      projectsLed: 12,
      teamSize: 8,
      yearsOfExperience: 10,
    },
  },
  {
    id: "account_manager_1",
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    role: "account_manager",
    teamId: "team-1",
    avatar:
      "https://ui-avatars.com/api/?name=Sarah+Wilson&background=8B5CF6&color=fff",
    department: "engineering",
    position: "Engineering Account Manager",
    phone: "+1 (555) 111-2222",
    location: "San Francisco, CA",
    bio: "Account manager for the Engineering team, focused on team performance and project delivery.",
    skills: ["Team Management", "Project Coordination", "Performance Analysis"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/sarahwilson",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "08:00",
      timezone: "America/Los_Angeles",
    },
    stats: {
      teamsLed: 1,
      projectsArchitected: 8,
      yearsOfExperience: 6,
    },
  },
  {
    id: "account_manager_2",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    role: "account_manager",
    teamId: "team-2",
    avatar:
      "https://ui-avatars.com/api/?name=Michael+Chen&background=EC4899&color=fff",
    department: "design",
    position: "Design Account Manager",
    phone: "+1 (555) 222-3333",
    location: "New York, NY",
    bio: "Account manager for the Design team, ensuring creative excellence and timely delivery.",
    skills: ["Design Management", "Creative Direction", "Client Relations"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/michaelchen",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "08:30",
      timezone: "America/New_York",
    },
    stats: {
      teamsLed: 1,
      projectsArchitected: 6,
      yearsOfExperience: 5,
    },
  },
  {
    id: "account_manager_3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    role: "account_manager",
    teamId: "team-3",
    avatar:
      "https://ui-avatars.com/api/?name=Emily+Rodriguez&background=F59E0B&color=fff",
    department: "marketing",
    position: "Marketing Account Manager",
    phone: "+1 (555) 333-4444",
    location: "Chicago, IL",
    bio: "Account manager for the Marketing team, driving growth and brand awareness.",
    skills: ["Marketing Strategy", "Campaign Management", "Analytics"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/emilyrodriguez",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "09:00",
      timezone: "America/Chicago",
    },
    stats: {
      teamsLed: 1,
      projectsArchitected: 10,
      yearsOfExperience: 7,
    },
  },
  {
    id: "account_manager_4",
    name: "David Thompson",
    email: "david.thompson@example.com",
    role: "account_manager",
    teamId: "team-4",
    avatar:
      "https://ui-avatars.com/api/?name=David+Thompson&background=10B981&color=fff",
    department: "sales",
    position: "Sales Account Manager",
    phone: "+1 (555) 444-5555",
    location: "Austin, TX",
    bio: "Account manager for the Sales team, maximizing revenue and customer satisfaction.",
    skills: ["Sales Management", "Revenue Optimization", "Customer Relations"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/davidthompson",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "08:00",
      timezone: "America/Chicago",
    },
    stats: {
      teamsLed: 1,
      projectsArchitected: 12,
      yearsOfExperience: 8,
    },
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "employee",
    teamId: "team-2",
    avatar:
      "https://ui-avatars.com/api/?name=Jane+Smith&background=6366F1&color=fff",
    department: "design",
    position: "Senior UI/UX Designer",
    phone: "+1 (555) 234-5678",
    location: "New York, NY",
    bio: "Creative designer focused on creating beautiful and intuitive user experiences.",
    skills: ["UI/UX", "Figma", "Adobe XD", "User Research", "Prototyping"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/janesmith",
      dribbble: "https://dribbble.com/janesmith",
      behance: "https://behance.net/janesmith",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "08:30",
      timezone: "America/New_York",
    },
    stats: {
      designSystems: 5,
      completedProjects: 45,
      yearsOfExperience: 7,
    },
  },
  {
    id: "3",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "employee",
    teamId: "team-3",
    avatar:
      "https://ui-avatars.com/api/?name=Alice+Johnson&background=10B981&color=fff",
    department: "marketing",
    position: "Marketing Specialist",
    phone: "+1 (555) 345-6789",
    location: "Chicago, IL",
    bio: "Digital marketing expert specializing in growth strategies and content creation.",
    skills: [
      "Content Strategy",
      "SEO",
      "Social Media",
      "Email Marketing",
      "Analytics",
    ],
    socialLinks: {
      linkedin: "https://linkedin.com/in/alicejohnson",
      twitter: "https://twitter.com/alicejohnson",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "09:30",
      timezone: "America/Chicago",
    },
    stats: {
      campaigns: 24,
      contentPieces: 150,
      yearsOfExperience: 5,
    },
  },
  {
    id: "4",
    name: "Bob Wilson",
    email: "bob@example.com",
    role: "employee",
    teamId: "team-1",
    avatar:
      "https://ui-avatars.com/api/?name=Bob+Wilson&background=EF4444&color=fff",
    department: "engineering",
    position: "Senior Developer",
    phone: "+1 (555) 456-7890",
    location: "Austin, TX",
    bio: "Full-stack developer with expertise in modern web technologies and cloud architecture.",
    skills: ["Python", "AWS", "DevOps", "React", "Node.js", "MongoDB"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/bobwilson",
      github: "https://github.com/bobwilson",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "10:00",
      timezone: "America/Chicago",
    },
    stats: {
      codeReviews: 500,
      pullRequests: 300,
      yearsOfExperience: 8,
    },
  },
  {
    id: "5",
    name: "Sarah Chen",
    email: "sarah@example.com",
    role: "employee",
    teamId: "team-1",
    avatar:
      "https://ui-avatars.com/api/?name=Sarah+Chen&background=8B5CF6&color=fff",
    department: "engineering",
    position: "Technical Lead",
    phone: "+1 (555) 567-8901",
    location: "Seattle, WA",
    bio: "Experienced technical lead with expertise in system architecture, team leadership, and technical decision-making.",
    skills: [
      "System Architecture",
      "Team Leadership",
      "Technical Strategy",
      "Code Review",
      "Agile",
      "DevOps",
    ],
    socialLinks: {
      linkedin: "https://linkedin.com/in/sarahchen",
      github: "https://github.com/sarahchen",
      twitter: "https://twitter.com/sarahchen",
    },
    preferences: {
      workDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      reportTime: "08:00",
      timezone: "America/Los_Angeles",
    },
    stats: {
      teamsLed: 3,
      projectsArchitected: 15,
      yearsOfExperience: 12,
    },
    joinedDate: "2022-03-15",
    experience: "12+ years",
  },
  {
    id: "6",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    role: "employee",
    teamId: "team-2",
    avatar:
      "https://ui-avatars.com/api/?name=Jane+Doe&background=6366F1&color=fff",
    department: "design",
    position: "Junior Designer",
    phone: "+1 (555) 678-9012",
    location: "Boston, MA",
    bio: "Aspiring designer eager to learn and create beautiful designs.",
    skills: ["UI/UX", "Figma", "Adobe XD"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/janedoe",
    },
    preferences: {
      workDays: ["monday", "wednesday", "friday"],
      reportTime: "09:00",
      timezone: "America/New_York",
    },
    stats: {
      designSystems: 1,
      completedProjects: 10,
      yearsOfExperience: 2,
    },
  },
  {
    id: "7",
    name: "Mike Brown",
    email: "mike.brown@example.com",
    role: "employee",
    teamId: "team-3",
    avatar:
      "https://ui-avatars.com/api/?name=Mike+Brown&background=10B981&color=fff",
    department: "marketing",
    position: "Content Writer",
    phone: "+1 (555) 789-0123",
    location: "Miami, FL",
    bio: "Content writer with a knack for crafting engaging and SEO-friendly copy.",
    skills: ["Content Strategy", "SEO", "Social Media"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/mikebrown",
    },
    preferences: {
      workDays: ["tuesday", "thursday", "saturday"],
      reportTime: "10:00",
      timezone: "America/New_York",
    },
    stats: {
      contentPieces: 80,
      campaigns: 15,
      yearsOfExperience: 3,
    },
  },
  {
    id: "8",
    name: "Lisa Green",
    email: "lisa.green@example.com",
    role: "employee",
    teamId: "team-4",
    avatar:
      "https://ui-avatars.com/api/?name=Lisa+Green&background=EF4444&color=fff",
    department: "sales",
    position: "Sales Representative",
    phone: "+1 (555) 890-1234",
    location: "Dallas, TX",
    bio: "Sales representative with a strong track record of closing deals and building relationships.",
    skills: ["Lead Generation", "Negotiation", "CRM"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/lisagreen",
    },
    preferences: {
      workDays: ["monday", "wednesday", "friday"],
      reportTime: "09:00",
      timezone: "America/Chicago",
    },
    stats: {
      leadsGenerated: 120,
      dealsClosed: 25,
      yearsOfExperience: 4,
    },
  },
  {
    id: "9",
    name: "Tom White",
    email: "tom.white@example.com",
    role: "employee",
    teamId: "team-1",
    avatar:
      "https://ui-avatars.com/api/?name=Tom+White&background=8B5CF6&color=fff",
    department: "engineering",
    position: "Software Engineer",
    phone: "+1 (555) 901-2345",
    location: "Seattle, WA",
    bio: "Software engineer with expertise in React and Node.js, always eager to learn new technologies.",
    skills: ["React", "Node.js", "MongoDB"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/tomwhite",
    },
    preferences: {
      workDays: ["monday", "wednesday", "friday"],
      reportTime: "09:30",
      timezone: "America/Los_Angeles",
    },
    stats: {
      codeReviews: 200,
      pullRequests: 150,
      yearsOfExperience: 4,
    },
  },
  {
    id: "10",
    name: "Emma Davis",
    email: "emma.davis@example.com",
    role: "employee",
    teamId: "team-2",
    avatar:
      "https://ui-avatars.com/api/?name=Emma+Davis&background=10B981&color=fff",
    department: "design",
    position: "UI/UX Designer",
    phone: "+1 (555) 012-3456",
    location: "New York, NY",
    bio: "UI/UX designer with a keen eye for detail and user-centered design.",
    skills: ["UI/UX", "Figma", "Adobe XD"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/emmadavis",
    },
    preferences: {
      workDays: ["tuesday", "thursday", "saturday"],
      reportTime: "08:30",
      timezone: "America/New_York",
    },
    stats: {
      designSystems: 2,
      completedProjects: 20,
      yearsOfExperience: 3,
    },
  },
  {
    id: "11",
    name: "Peter Jones",
    email: "peter.jones@example.com",
    role: "employee",
    teamId: "team-3",
    avatar:
      "https://ui-avatars.com/api/?name=Peter+Jones&background=EF4444&color=fff",
    department: "marketing",
    position: "Content Strategist",
    phone: "+1 (555) 123-4567",
    location: "Chicago, IL",
    bio: "Content strategist with a background in SEO and social media content.",
    skills: ["Content Strategy", "SEO", "Social Media"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/peterjones",
    },
    preferences: {
      workDays: ["monday", "wednesday", "friday"],
      reportTime: "09:00",
      timezone: "America/Chicago",
    },
    stats: {
      contentPieces: 100,
      campaigns: 20,
      yearsOfExperience: 5,
    },
  },
  {
    id: "12",
    name: "Sophia Rodriguez",
    email: "sophia.rodriguez@example.com",
    role: "employee",
    teamId: "team-4",
    avatar:
      "https://ui-avatars.com/api/?name=Sophia+Rodriguez&background=8B5CF6&color=fff",
    department: "sales",
    position: "Sales Associate",
    phone: "+1 (555) 234-5678",
    location: "Austin, TX",
    bio: "Sales associate with a strong focus on customer service and relationship building.",
    skills: ["Lead Generation", "Negotiation", "CRM"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/sophiarodriguez",
    },
    preferences: {
      workDays: ["monday", "wednesday", "friday"],
      reportTime: "08:30",
      timezone: "America/Chicago",
    },
    stats: {
      leadsGenerated: 80,
      dealsClosed: 15,
      yearsOfExperience: 3,
    },
  },
  {
    id: "13",
    name: "James Wilson",
    email: "james.wilson@example.com",
    role: "employee",
    teamId: "team-1",
    avatar:
      "https://ui-avatars.com/api/?name=James+Wilson&background=10B981&color=fff",
    department: "engineering",
    position: "Frontend Developer",
    phone: "+1 (555) 345-6789",
    location: "San Francisco, CA",
    bio: "Frontend developer with a passion for creating intuitive and responsive user interfaces.",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/jameswilson",
    },
    preferences: {
      workDays: ["monday", "wednesday", "friday"],
      reportTime: "09:30",
      timezone: "America/Los_Angeles",
    },
    stats: {
      codeReviews: 150,
      pullRequests: 100,
      yearsOfExperience: 3,
    },
  },
];

export const mockProjects = [
  {
    id: "1",
    name: "Website Redesign",
    description: "Complete redesign of the company website",
    startDate: "2024-01-15",
    endDate: "2024-03-15",
    status: "progress",
    progress: 65,
    teamMembers: ["2", "3"],
    createdBy: "1",
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    name: "Mobile App Development",
    description: "Development of the iOS and Android mobile application",
    startDate: "2024-02-01",
    endDate: "2024-05-01",
    status: "progress",
    progress: 30,
    teamMembers: ["4", "2"],
    createdBy: "1",
    createdAt: "2024-01-25",
  },
  {
    id: "3",
    name: "Marketing Campaign",
    description: "Q1 marketing campaign planning and execution",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
    status: "completed",
    progress: 100,
    teamMembers: ["3"],
    createdBy: "1",
    createdAt: "2023-12-15",
  },
];

export const mockTasks = [
  {
    id: "1",
    title: "Create wireframes for homepage",
    description: "Design initial wireframes for the new homepage layout",
    status: "todo",
    priority: "high",
    assignee: "2",
    project: "1",
    dueDate: "2024-01-20",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    createdBy: "1",
  },
  {
    id: "2",
    title: "Implement user authentication",
    description: "Set up user login and registration system",
    status: "progress",
    priority: "urgent",
    assignee: "4",
    project: "2",
    dueDate: "2024-02-10",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-05",
    createdBy: "1",
  },
  {
    id: "3",
    title: "Write unit tests",
    description:
      "Create comprehensive unit tests for the authentication module",
    status: "review",
    priority: "medium",
    assignee: "2",
    project: "2",
    dueDate: "2024-02-15",
    createdAt: "2024-02-08",
    updatedAt: "2024-02-12",
    createdBy: "1",
  },
  {
    id: "4",
    title: "Design marketing materials",
    description: "Create brochures and digital assets for the campaign",
    status: "completed",
    priority: "medium",
    assignee: "3",
    project: "3",
    dueDate: "2024-01-25",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-24",
    createdBy: "1",
  },
  {
    id: "5",
    title: "Setup database schema",
    description: "Design and implement the database structure",
    status: "progress",
    priority: "high",
    assignee: "4",
    project: "2",
    dueDate: "2024-02-05",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    createdBy: "1",
  },
  {
    id: "6",
    title: "Content creation",
    description: "Write and optimize content for the new website",
    status: "review",
    priority: "medium",
    assignee: "3",
    project: "1",
    dueDate: "2024-02-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15",
    createdBy: "1",
  },
  {
    id: "7",
    title: "Content creation",
    description: "Write and optimize content for the new website",
    status: "completed",
    priority: "medium",
    assignee: "3",
    project: "1",
    dueDate: "2024-02-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15",
    createdBy: "1",
  },
  {
    id: "8",
    title: "Content creation",
    description: "Write and optimize content for the new website",
    status: "todo",
    priority: "medium",
    assignee: "3",
    project: "1",
    dueDate: "2024-02-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-15",
    createdBy: "1",
  },
];

export const mockConversations = [
  {
    id: "1",
    name: "Development Team",
    type: "group",
    participants: ["1", "2", "4"],
    lastMessage: "Great progress on the authentication module!",
    lastMessageTime: "2024-01-15 14:30",
    unreadCount: 2,
  },
  {
    id: "2",
    name: "Jane Smith",
    type: "individual",
    participants: ["1", "2"],
    lastMessage: "Can we schedule a meeting to discuss the wireframes?",
    lastMessageTime: "2024-01-15 11:20",
    unreadCount: 1,
  },
  {
    id: "3",
    name: "Project Updates",
    type: "group",
    participants: ["1", "2", "3", "4"],
    lastMessage: "Marketing campaign is now complete!",
    lastMessageTime: "2024-01-14 16:45",
    unreadCount: 0,
  },
];

export const mockMessages = [
  {
    id: "1",
    conversationId: "1",
    senderId: "1",
    content: "Good morning team! How is everyone doing with their tasks?",
    timestamp: "2024-01-15 09:00",
    type: "text",
  },
  {
    id: "2",
    conversationId: "1",
    senderId: "4",
    content:
      "Working on the authentication module. Should be ready for testing by tomorrow.",
    timestamp: "2024-01-15 09:15",
    type: "text",
  },
  {
    id: "3",
    conversationId: "1",
    senderId: "2",
    content:
      "Wireframes are coming along nicely. Will share them this afternoon.",
    timestamp: "2024-01-15 09:30",
    type: "text",
  },
  {
    id: "4",
    conversationId: "1",
    senderId: "1",
    content: "Great progress on the authentication module!",
    timestamp: "2024-01-15 14:30",
    type: "text",
  },
  {
    id: "5",
    conversationId: "2",
    senderId: "2",
    content:
      "Hi John, I have completed the initial wireframes for the homepage.",
    timestamp: "2024-01-15 10:00",
    type: "text",
  },
  {
    id: "6",
    conversationId: "2",
    senderId: "1",
    content: "That's excellent! Could you share them with me?",
    timestamp: "2024-01-15 10:15",
    type: "text",
  },
  {
    id: "7",
    conversationId: "2",
    senderId: "2",
    content: "Can we schedule a meeting to discuss the wireframes?",
    timestamp: "2024-01-15 11:20",
    type: "text",
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "task_completed",
    title: "Task Completed",
    message: 'Jane Smith completed "Design marketing materials"',
    timestamp: "2024-01-15 14:30",
    read: false,
    userId: "1",
  },
  {
    id: "2",
    type: "task_assigned",
    title: "New Task Assigned",
    message: 'You have been assigned to "Create wireframes for homepage"',
    timestamp: "2024-01-15 09:00",
    read: false,
    userId: "2",
  },
  {
    id: "3",
    type: "project_created",
    title: "New Project Created",
    message: "Mobile App Development project has been created",
    timestamp: "2024-01-14 16:00",
    read: true,
    userId: "1",
  },
];

export const generateMockData = () => {
  return {
    users: mockUsers,
    projects: mockProjects,
    tasks: mockTasks,
    conversations: mockConversations,
    messages: mockMessages,
    notifications: mockNotifications,
  };
};
